# Book settings
title: Book of Code
author: Sean Cahill
logo: "default.png"

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web

repository url: https://github.com/Amadreyfus/BookOfCode
